### PR TITLE
Fix #1052

### LINKED ISSUE #1052: SeaweedFS & Empty directories
Hi @drakkan 
First of all, thank you for wonderful work that you done here :heart: 

# Problem
I started an s3 service using [Seaweedfs](https://github.com/seaweedfs/seaweedfs) and a sftpgo instance with ftp enabled.
When I connect to ftp i can list/get/... my files but when I create a new directory using mkdir command I cannot change directory to it.
```
# ftp sftpgo
Connected to sftpgo.
Name (sftpgo:root): my-user
331 OK
Password:
230 Password ok, continue
Remote system type is UNIX.
Using binary mode to transfer files.

ftp> mkdir test
257 Created dir "/test"

ftp> cd test
550 Can't change directory to /test: Not a Directory
```

# Reproduce
You can follow these steps to reproduce the problem:

install seaweedfs
```
cd /tmp
wget https://github.com/seaweedfs/seaweedfs/releases/download/3.34/linux_amd64.tar.gz
tar -xvf linux_amd64.tar.gz
./weed server -filer -s3
```

In Another shell terminal:
```
./weed shell
> s3.configure -user admin -access_key admin -secret_key 123456 -actions Read,Write,List,Tagging,Admin  -apply
> s3.bucket.create -name my-bucket
```

Now spin up a portable sftpgo instance with ftp access:
```
sftpgo portable --fs-provider s3fs  --s3-access-key admin --s3-access-secret 123456 --s3-bucket my-bucket --s3-endpoint http://localhost:8333 --s3-force-path-style --ftpd-port 21 --sftpd-port -1
```

Now you connect with ftp client:
```
ftp localhost
220 SFTPGo portable 2.4.0 ready
Name (localhost:root): admin
331 OK
Password:
230 Password ok, continue
Remote system type is UNIX.
Using binary mode to transfer files.
> mkdir test
257 Created dir "/test"

ftp> cd test
550 Can't change directory to /test: Not a Directory
```

# Cuase
Because Seaweedfs actually have & support directories unlike S3, objects cannot have '/' in their name.
As far as I know sftpgo rely on '/' in object name to detect whether an object is empty directory or not.

# Suggested Solution
in [internal/vfs/s3fs.go:162](https://github.com/drakkan/sftpgo/blob/a9207857cf53d379a1b73a8dfd60ac8e16faecab/internal/vfs/s3fs.go#L162) we can check for  `application/x-directory` mimetype.
```diff
obj, err := fs.headObject(name)
if err == nil {
-	// a "dir" has a trailing "/" so we cannot have a directory here
+	isDir := *obj.ContentType == s3DirMimeType
-	return updateFileInfoModTime(fs.getStorageID(), name, NewFileInfo(name, false, obj.ContentLength,
+	return updateFileInfoModTime(fs.getStorageID(), name, NewFileInfo(name, isDir, obj.ContentLength,
		util.GetTimeFromPointer(obj.LastModified), false))
}
```

### PR DESCRIPTION
**Pull request by yeganemehr**

### CODE REVIEW

File: internal/vfs/s3fs.go [hunk 1]
```diff
@@ -159,8 +159,8 @@ func (fs *S3Fs) Stat(name string) (os.FileInfo, error) {
 	}
 	obj, err := fs.headObject(name)
 	if err == nil {
-		// a "dir" has a trailing "/" so we cannot have a directory here
-		return updateFileInfoModTime(fs.getStorageID(), name, NewFileInfo(name, false, obj.ContentLength,
+		isDir := *obj.ContentType == s3DirMimeType
```
Comment (drakkan) [inline internal/vfs/s3fs.go:162]: Please use `util.GetStringFromPointer(obj.ContentType)`

**Comment by drakkan** [comment]
Please also fix the [DCO](https://github.com/drakkan/sftpgo/pull/1053/checks?check_run_id=9453457688) check. Thanks

File: internal/vfs/s3fs.go (hunk 1 above)
Comment (drakkan) [reply internal/vfs/s3fs.go:162]: also add a comment explaining why we may not have the trailing slash and so we check the mime type

Comment (hosni) [reply internal/vfs/s3fs.go:162]: > Please use `util.GetStringFromPointer(obj.ContentType)`

It's so important to use util, because it can throw:
`invalid memory address or nil pointer dereference` error on FTP put or FTP size.

`{"level":"warn","time":"2022-11-15T13:41:39.737","sender":"ftpserverlib","server_id":"FTP_0","clientId":"8","err":"runtime error: invalid memory address or nil pointer dereference","command":"SIZE","param":"/some-file","message":"Internal command handling error"}`

Comment (yeganemehr) [reply internal/vfs/s3fs.go]: I did as you requested.

**Comment by drakkan** [comment]
thanks!

**Comment by drakkan** [comment]
Hello,

thank you again for this contribution. We have recently updated our contribution policy and we now require signing a CLA. Agreeing to the CLA clarifies your rights as a contributor and at the same time protects SFTPGo and its users.

More details [here](https://sftpgo.com/cla.html)

You can use the following URL to sign the CLA

https://cla-assistant.io/drakkan/sftpgo?pullRequest=1053

The contributed code has been rewritten but we would still greatly appreciate it if you could sign the CLA.
Thank you!
